<# ::
@ECHO OFF
CLS
SETLOCAL ENABLEDELAYEDEXPANSION
CHCP 65001 >NUL
MODE 120, 30 >NUL
 
:: Copyright (C) 2025 HeeminTV

:: This program is free software; you can redistribute it and/or
:: modify it under the terms of the GNU General Public License
:: as published by the Free Software Foundation; either version 2
:: of the License, or (at your option) any later version.

:: This program is distributed in the hope that it will be useful,
:: but WITHOUT ANY WARRANTY; without even the implied warranty of
:: MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
:: GNU General Public License for more details.

:: You should have received a copy of the GNU General Public License
:: along with this program; if not, see <https://www.gnu.org/licenses/>.

:: PROGRAM INFORMATION (DO NOT EDIT THIS) ::
SET "SY_APPNAME=SaeyahnTracker"
SET "SY_VERSION=DEV VERSION"
SET "SY_EXT=.sy;.sytm"
SET "SY_APPCONFIGPATH=!APPDATA!\SaeyahnTracer-Rewritten"
SET /A "SY_MODULE_TRACKER_VER=0x0000"
SET /A "SY_MODULE_FORMAT_VER=0x0000"
SET "SY_APPID=!RANDOM!!RANDOM!"

:: REGISTER EXTENSIONS ::
FOR %%A IN (!SY_EXT!) DO (
	ASSOC %%A=SaeyahnTrackerModule%%A 2>NUL >NUL
	FTYPE SaeyahnTrackerModule%%A="%~0" "%%1" 2>NUL >NUL
)

:: MACROS ::
SET "WHILE=FOR /L %%Z IN (1 1 16) DO IF DEFINED DO.WHILE"
SET "WHILE=SET DO.WHILE=1&!WHILE! !WHILE! !WHILE! !WHILE! !WHILE! "
SET "BREAK=SET "DO.WHILE=""
SET "KEYINPUT=powershell "exit($Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown').VirtualKeyCode)""

:: LOAD / CREATE CONFIGURATION ::
REM -- COLOR, PATTERNS --
SET "SYCONFIG_COLOR_CHTBG=64;64;96"
SET "SYCONFIG_COLOR_PATBG=24;34;51"
SET "SYCONFIG_COLOR_PATH1=54;64;81"
SET "SYCONFIG_COLOR_PATH2=64;84;101"
SET "SYCONFIG_COLOR_CURPV=64;64;192"
SET "SYCONFIG_COLOR_CURRC=128;64;64"

REM -- COLOR, CHARACTERS --
SET "SYCONFIG_COLOR_PDTXT=180;180;180"
SET "SYCONFIG_COLOR_P1TXT=192;192;192"
SET "SYCONFIG_COLOR_P2TXT=204;204;204"
SET "SYCONFIG_COLOR_CTTXT=204;204;204"
SET "SYCONFIG_COLOR_MTTXT=204;204;204"
SET "SYCONFIG_COLOR_SITXT=204;204;204"
SET "SYCONFIG_COLOR_LGTXT=204;204;204"

REM -- COLOR, OTHERS --
SET "SYCONFIG_COLOR_MJTAB=8;8;64"
SET "SYCONFIG_COLOR_SITAB=0;0;0"
SET "SYCONFIG_COLOR_LBASE=204;204;204"

REM -- OTHERS --
SET "SYCONFIG_TERMINALISH_MODE=BREAK"

IF NOT EXIST "!SY_APPCONFIGPATH!\config.txt" (
	MKDIR "!SY_APPCONFIGPATH!" 2>NUL >NUL
	CALL :SAVE_CONFIG
)

FOR /F "USEBACKQ TOKENS=1,2 DELIMS==" %%A IN ("!SY_APPCONFIGPATH!\config.txt") DO SET "%%A=%%B"

:: CHECK DEPENDENCIES ::
RWIB.EXE 2>NUL >NUL
IF !ERRORLEVEL! EQU 9009 (
	CALL :MSGBOX "Couldn't find RWIB installed! Please download RWIB and put in the same directory with this tracker or in the one of the directories of PATH! Press OK to go to the download page." 16 1
	IF !TEMPVARI00! EQU 1 START https://github.com/HeeminTV/RWIB/releases
	EXIT /B 1
)

:: ARGUMENT HANDLER ::
SET "SY_CURRMODULE=%~1"
CALL :NEW_SONG
IF EXIST "!SY_CURRMODULE!" CALL :LOAD_MODULE

:: DRAW_TRACKER should be called when:
REM -- Loaded new song
REM -- Closed any kinds of dialogue
REM -- Rows / Pattern count has been changed in any ways (Appending / resize etc)
REM -- TRACKER_MODE got updated
:DRAW_TRACKER
CALL :UPDATE_PATTERN_COUNTER
ECHO [H[0m[48;2;!SYCONFIG_COLOR_MJTAB!m[38;2;!SYCONFIG_COLOR_MTTXT!m┌[7m[F7][27m─ Main Tab ──────────────────────────────────────────────────────────────────────────────────────────────────────┐[2;1H└──[7m[N][27m_New──[7m[O][27m_Open──[7m[S][27m_Save──[7m[C][27m_Save as──[7m[R][27m_Render──[7m[M][27m_Export as .xm──[7m[T][27m_Configuration / About─────────────────┘ 
ECHO [3;1H[48;2;!SYCONFIG_COLOR_SITAB!m[38;2;!SYCONFIG_COLOR_SITXT!m┌[7m[F3][27m─ Song Information ──────────────────────────────────────────────────────────────────────────────────────────────┐[11;11HTracker Version !SY_VERSION![12;1H└──  You are in [5m!TRACKER_MODE![25m─────────────────────────────────────────────────────────────────────────────────────┘ 
FOR /L %%A IN (4,1,11) DO ECHO [%%A;1H│[%%A;119H│ 
ECHO [4;48H[7m[B][27m_BPM        : !SYMODULE_TEMPO![5;48H[7m[R][27m_Rows       : !SYMODULE_ROWS![6;48H[7m[H][27m_Highlight  : !SYMODULE_HIGHLIGHT![7;48H[7m[S][27m_Edit Step  : !EDITSTEP![4;72H[7m[S][27m_Song Title :[5;72H[7m[S][27m_Song Author:[4m[4;89H                             [5;89H                             [4;89H!SYMODULE_SONGTITLE![5;89H!SYMODULE_SONGAUTHOR![24m
CALL :DRAW_LOGO_AT 4 4
ECHO [13;1H[48;2;!SYCONFIG_COLOR_CHTBG!m[38;2;!SYCONFIG_COLOR_CTTXT!m┌[7m[F1][27m─ Tracker Section ─────────────────────────────────────────────────────────────────────────────────────────┬─────┐[14;1H├──[7m[A][27m_Samples──[7m[\][27m_Frames──────────┬─┬────────────────┬─┬────────────────┬─┬────────────────┬─┬────────────────┤ PAT │[16;115H----│
FOR /L %%A IN (1,1,6) DO (
    SET /A "TEMPVARI01=((%%A - 1) * 19) + 1"
    ECHO [15;!TEMPVARI01!H│ Channel %%A  ___ │:[16;!TEMPVARI01!H│----------------│-
)
!SYCONFIG_TERMINALISH_MODE!

:EDIT
ECHO [48;2;!SYCONFIG_COLOR_CHTBG!m[38;2;!SYCONFIG_COLOR_CTTXT!m[15;116H   │[15;114H!CURSOR_FRAME!/!PATTERN_COUNTER![16;1H
SET /A "ROWCURR=SYMODULE_ROWS - 6"
IF !CURSOR_ROWS! LSS 6 (
	SET "DISPLAY_START=0"
) ELSE IF !CURSOR_ROWS! GEQ !ROWCURR! (
	SET /A "DISPLAY_START=SYMODULE_ROWS - 13"
) ELSE (
	SET /A "DISPLAY_START=CURSOR_ROWS - 6"
)
SET /A "DISPLAY_END=DISPLAY_START + 12,ROWCURR=-1"
FOR %%A IN (!SYMODULE_PAT%CURSOR_FRAME%!) DO SET /A "ROWCURR+=1" & IF !ROWCURR! GEQ !DISPLAY_START! IF !ROWCURR! LEQ !DISPLAY_END! (
	SET "ROWCONTEXT=%%A"
	SET /A "TEMPVARI01=^!(ROWCURR %% SYMODULE_HIGHLIGHT) + ^!(ROWCURR %% (SYMODULE_HIGHLIGHT << 1)),TEMPVARI02=((CURSOR_X >> 3) * 12) + ((1 - ^!(ROWCURR - CURSOR_ROWS)) * 100),TEMPVARI03=CURSOR_X & 7"
	IF !ROWCURR! EQU !CURSOR_ROWS! (
		IF !CURSOR_MODE! EQU 1 (
			SET "ROWCOLOR=[48;2;!SYCONFIG_COLOR_CURRC!m[38;2;!SYCONFIG_COLOR_PDTXT!m"
		) ELSE (
			SET "ROWCOLOR=[48;2;!SYCONFIG_COLOR_CURPV!m[38;2;!SYCONFIG_COLOR_PDTXT!m"
		)
	) ELSE (
		IF !TEMPVARI01! EQU 2 (
			SET "ROWCOLOR=[48;2;!SYCONFIG_COLOR_PATH2!m[38;2;!SYCONFIG_COLOR_P2TXT!m"
		) ELSE IF !TEMPVARI01! EQU 1 (
			SET "ROWCOLOR=[48;2;!SYCONFIG_COLOR_PATH1!m[38;2;!SYCONFIG_COLOR_P1TXT!m"
		) ELSE (
			SET "ROWCOLOR=[48;2;!SYCONFIG_COLOR_PATBG!m[38;2;!SYCONFIG_COLOR_PDTXT!m"
		)
	)
	
	SET "ROWLINE=!ROWCOLOR!│"
	FOR /L %%B IN (0, 12, 71) DO (
		SET "TEMPVARI00=!ROWCONTEXT:~%%B,12!"
		IF %%B EQU !TEMPVARI02! (
			IF !TEMPVARI03! EQU 0 (
				SET "ROWLINE=!ROWLINE![7m!TEMPVARI00:~0,3![27m:!TEMPVARI00:~3,2!:!TEMPVARI00:~5,1!:!TEMPVARI00:~6,3!:!TEMPVARI00:~9,3!│:│"
			) ELSE IF !TEMPVARI03! EQU 1 (
				SET "ROWLINE=!ROWLINE!!TEMPVARI00:~0,3!:[7m!TEMPVARI00:~3,1![27m!TEMPVARI00:~4,1!:!TEMPVARI00:~5,1!:!TEMPVARI00:~6,3!:!TEMPVARI00:~9,3!│:│"
			) ELSE IF !TEMPVARI03! EQU 2 (
				SET "ROWLINE=!ROWLINE!!TEMPVARI00:~0,3!:!TEMPVARI00:~3,1![7m!TEMPVARI00:~4,1![27m:!TEMPVARI00:~5,1!:!TEMPVARI00:~6,3!:!TEMPVARI00:~9,3!│:│"
			) ELSE IF !TEMPVARI03! EQU 3 (
				SET "ROWLINE=!ROWLINE!!TEMPVARI00:~0,3!:!TEMPVARI00:~3,2!:[7m!TEMPVARI00:~5,1![27m:!TEMPVARI00:~6,3!:!TEMPVARI00:~9,3!│:│"
			) ELSE IF !TEMPVARI03! EQU 4 (
				SET "ROWLINE=!ROWLINE!!TEMPVARI00:~0,3!:!TEMPVARI00:~3,2!:!TEMPVARI00:~5,1!:[7m!TEMPVARI00:~6,1![27m!TEMPVARI00:~7,2!:!TEMPVARI00:~9,3!│:│"
			) ELSE IF !TEMPVARI03! EQU 5 (
				SET "ROWLINE=!ROWLINE!!TEMPVARI00:~0,3!:!TEMPVARI00:~3,2!:!TEMPVARI00:~5,1!:!TEMPVARI00:~6,1![7m!TEMPVARI00:~7,2![27m:!TEMPVARI00:~9,3!│:│"
			) ELSE IF !TEMPVARI03! EQU 6 (
				SET "ROWLINE=!ROWLINE!!TEMPVARI00:~0,3!:!TEMPVARI00:~3,2!:!TEMPVARI00:~5,1!:!TEMPVARI00:~6,3!:[7m!TEMPVARI00:~9,1![27m!TEMPVARI00:~10,2!│:│"
			) ELSE IF !TEMPVARI03! EQU 7 (
				SET "ROWLINE=!ROWLINE!!TEMPVARI00:~0,3!:!TEMPVARI00:~3,2!:!TEMPVARI00:~5,1!:!TEMPVARI00:~6,3!:!TEMPVARI00:~9,1![7m!TEMPVARI00:~10,2![27m│:│"
			)
		) ELSE (
			SET "ROWLINE=!ROWLINE!!TEMPVARI00:~0,3!:!TEMPVARI00:~3,2!:!TEMPVARI00:~5,1!:!TEMPVARI00:~6,3!:!TEMPVARI00:~9,3!│:│"
		)
	)
	ECHO !ROWLINE![114G [7m !ROWCURR! [27m[119G│[0m
)

%KEYINPUT%
IF !ERRORLEVEL! EQU 38 SET /A "CURSOR_ROWS-=EDITSTEP"
IF !ERRORLEVEL! EQU 40 SET /A "CURSOR_ROWS+=EDITSTEP"
IF !ERRORLEVEL! EQU 36 SET "CURSOR_ROWS=0"
IF !ERRORLEVEL! EQU 35 SET /A "CURSOR_ROWS=SYMODULE_ROWS - 1"
IF !ERRORLEVEL! EQU 33 SET /A "CURSOR_ROWS-=SYMODULE_HIGHLIGHT"
IF !ERRORLEVEL! EQU 34 SET /A "CURSOR_ROWS+=SYMODULE_HIGHLIGHT"

IF !ERRORLEVEL! EQU 39 SET /A "CURSOR_X+=1"
IF !ERRORLEVEL! EQU 37 SET /A "CURSOR_X-=1"
IF !ERRORLEVEL! EQU 9 SET /A "CURSOR_X=((CURSOR_X + 8) >> 3) << 3"

IF !CURSOR_ROWS! LSS 0 SET /A "CURSOR_ROWS+=SYMODULE_ROWS"
IF !CURSOR_ROWS! GEQ !SYMODULE_ROWS! SET /A "CURSOR_ROWS-=SYMODULE_ROWS"
IF !CURSOR_ROWS! LSS 0 SET "CURSOR_ROWS=0"
IF !CURSOR_ROWS! GEQ !SYMODULE_ROWS! SET /A "CURSOR_ROWS=SYMODULE_ROWS - 1"
IF !CURSOR_X! LSS 0 SET /A "CURSOR_X+=48"
IF !CURSOR_X! GEQ 48 SET /A "CURSOR_X-=48"

IF !ERRORLEVEL! EQU 32 SET /A "CURSOR_MODE=(CURSOR_MODE + 1) & 1"
IF !ERRORLEVEL! EQU 13 CALL :PLAY "%~0"
GOTO EDIT

:: FUNCTIONS (CALL ONLY) ::
:NEW_SONG
SET "SYMODULE_TEMPO=150"
SET "SYMODULE_ROWS=64"
SET "SYMODULE_HIGHLIGHT=4"
SET "SYMODULE_SONGTITLE=New song"
SET "SYMODULE_SONGAUTHOR=Jack"
FOR /L %%A IN (0, 1, 255) DO SET "SYMODULE_PAT%%A="
CALL :RESET
CALL :CREATE_PATTERN 0
CALL :UPDATE_PATTERN_COUNTER
GOTO :EOF

:RESET
SET "EDITSTEP=1"
SET "CURSOR_FRAME=0"
SET "CURSOR_X=0"
SET "CURSOR_ROWS=0"
SET "CURSOR_MODE=0"
SET "TRACKER_MODE=Tracker section  "
GOTO :EOF

:PLAY PATH_OF_THIS_SCRIPT
SET /A "CURSOR_MODE<<=1"
SET "CURSOR_ROWS=0"
ECHO !SY_APPID! > "!SY_APPCONFIGPATH!\!SY_APPID!.stat"
START /MIN powershell -c "iex ((Get-Content '%~1') -join [Environment]::Newline); iex 'main \"!SY_APPCONFIGPATH!\!SY_APPID!.stat\"'"
TIMEOUT 0 >NUL
%WHILE% (
	ECHO [48;2;!SYCONFIG_COLOR_CHTBG!m[38;2;!SYCONFIG_COLOR_CTTXT!m[15;116H   │[15;114H!CURSOR_FRAME!/!PATTERN_COUNTER![16;1H
	SET /A "ROWCURR=SYMODULE_ROWS - 6"
	IF !CURSOR_ROWS! LSS 6 (
		SET "DISPLAY_START=0"
	) ELSE IF !CURSOR_ROWS! GEQ !ROWCURR! (
		SET /A "DISPLAY_START=SYMODULE_ROWS - 13"
	) ELSE (
		SET /A "DISPLAY_START=CURSOR_ROWS - 6"
	)
	SET /A "DISPLAY_END=DISPLAY_START + 12,ROWCURR=-1"
	FOR %%A IN (!SYMODULE_PAT%CURSOR_FRAME%!) DO SET /A "ROWCURR+=1" & IF !ROWCURR! GEQ !DISPLAY_START! IF !ROWCURR! LEQ !DISPLAY_END! (
		SET "ROWCONTEXT=%%A"
		SET /A "TEMPVARI01=^!(ROWCURR %% SYMODULE_HIGHLIGHT) + ^!(ROWCURR %% (SYMODULE_HIGHLIGHT << 1))"
		IF !ROWCURR! EQU !CURSOR_ROWS! (
			SET "ROWCOLOR=[48;2;!SYCONFIG_COLOR_CURPV!m[38;2;!SYCONFIG_COLOR_PDTXT!m"
		) ELSE (
			IF !TEMPVARI01! EQU 2 (
				SET "ROWCOLOR=[48;2;!SYCONFIG_COLOR_PATH2!m[38;2;!SYCONFIG_COLOR_P2TXT!m"
			) ELSE IF !TEMPVARI01! EQU 1 (
				SET "ROWCOLOR=[48;2;!SYCONFIG_COLOR_PATH1!m[38;2;!SYCONFIG_COLOR_P1TXT!m"
			) ELSE (
				SET "ROWCOLOR=[48;2;!SYCONFIG_COLOR_PATBG!m[38;2;!SYCONFIG_COLOR_PDTXT!m"
			)
		)
		
		ECHO !ROWCOLOR!│!ROWCONTEXT:~0,3!:!ROWCONTEXT:~3,2!:!ROWCONTEXT:~5,1!:!ROWCONTEXT:~6,3!:!ROWCONTEXT:~9,3!│:│^
!ROWCONTEXT:~12,3!:!ROWCONTEXT:~15,2!:!ROWCONTEXT:~17,1!:!ROWCONTEXT:~18,3!:!ROWCONTEXT:~21,3!│:│^
!ROWCONTEXT:~24,3!:!ROWCONTEXT:~27,2!:!ROWCONTEXT:~29,1!:!ROWCONTEXT:~30,3!:!ROWCONTEXT:~33,3!│:│^
!ROWCONTEXT:~36,3!:!ROWCONTEXT:~39,2!:!ROWCONTEXT:~41,1!:!ROWCONTEXT:~42,3!:!ROWCONTEXT:~45,3!│:│^
!ROWCONTEXT:~48,3!:!ROWCONTEXT:~51,2!:!ROWCONTEXT:~53,1!:!ROWCONTEXT:~54,3!:!ROWCONTEXT:~57,3!│:│^
!ROWCONTEXT:~60,3!:!ROWCONTEXT:~63,2!:!ROWCONTEXT:~65,1!:!ROWCONTEXT:~66,3!:!ROWCONTEXT:~69,3!│ [7m !ROWCURR!  [27m[119G│
	)
	SET /A "CURSOR_ROWS=((CURSOR_ROWS + 1) & 63)"
	IF NOT EXIST "!SY_APPCONFIGPATH!\!SY_APPID!.stat" %BREAK%
)
SET /A "CURSOR_MODE>>=1"
TIMEOUT 1 >NUL
GOTO :EOF

REM PATTERN_COUNTER
:UPDATE_PATTERN_COUNTER
SET "PATTERN_COUNTER=-1"
FOR /L %%A IN (0, 1, 255) DO IF DEFINED SYMODULE_PAT%%A SET /A "PATTERN_COUNTER+=1"
GOTO :EOF

:CREATE_PATTERN #
SET "SYMODULE_PAT%~1="
FOR /L %%A IN (0, 1, !SYMODULE_ROWS!) DO (
	FOR /L %%B IN (0, 1, 5) DO SET "SYMODULE_PAT%~1=!SYMODULE_PAT%~1!C#3_________"
	SET "SYMODULE_PAT%~1=!SYMODULE_PAT%~1!;"
)
GOTO :EOF

REM 00
:DELETE_PATTERN #
IF NOT DEFINED SYMODULE_PAT%~1 GOTO :EOF
FOR /L %%A IN (0, 1, !PATTERN_COUNTER!) DO (
	SET /A "TEMPVARI00=%%A - 1"
	IF %%A GEQ %~1 SET "SYMODULE_PAT!TEMPVARI00!=!SYMODULE_PAT%%A!"
)
GOTO :EOF

REM 00 01
:SET_ROWS TARGET
IF %~1 EQU !SYMODULE_ROWS! GOTO :EOF
FOR /L %%A IN (0, 1, 255) DO IF DEFINED "SYMODULE_PAT%%A" (
	IF %~1 LSS !SYMODULE_ROWS! (
		SET "TEMPVARI00=0"
		SET "TEMPVARI01="
		FOR %%B IN (!SYMODULE_PAT%%A!) DO (
			IF !TEMPVARI00! LSS %~1 SET "TEMPVARI01=!TEMPVARI01!%%B;"
			SET /A "TEMPVARI00+=1"
		)
		SET "SYMODULE_PAT%%A=!TEMPVARI01"
	) ELSE (
		SET /A "TEMPVARI01=%~1 - SYMODULE_ROWS"
		FOR /L %%B IN (1, 1, !TEMPVARI01!) DO (
			FOR /L %%C IN (0, 1, 5) DO SET "SYMODULE_PAT%%A=!SYMODULE_PAT%%A!____________"
			SET "SYMODULE_PAT%%A=!SYMODULE_PAT%%A!;"
		)
	)
)
SET "SYMODULE_ROWS=%~1"
GOTO :EOF

REM 00 01 02 03 04 05
:DRAW_LOGO_AT X Y
FOR /F "TOKENS=1,2,3 DELIMS=;" %%A IN ("!SYCONFIG_COLOR_LBASE!") DO (
	SET /A "TEMPVARI00=%%A / 2,TEMPVARI01=%%B / 2,TEMPVARI02=%%C / 2"
	SET /A "TEMPVARI03=TEMPVARI00 / 6,TEMPVARI04=TEMPVARI01 / 6,TEMPVARI05=TEMPVARI02 / 6"
)
ECHO [%~2;%~1H[38;2;!TEMPVARI00!;!TEMPVARI01!;!TEMPVARI02!m________________\[38;2;!SYCONFIG_COLOR_LGTXT!mSAEYAHN[38;2;!TEMPVARI00!;!TEMPVARI01!;!TEMPVARI02!m/________________ 
SET /A "TEMPVARI00+=TEMPVARI03,TEMPVARI01+=TEMPVARI04,TEMPVARI02+=TEMPVARI05"
ECHO [%~1G[38;2;!TEMPVARI00!;!TEMPVARI01!;!TEMPVARI02!m^|                \     /                ^| 
SET /A "TEMPVARI00+=TEMPVARI03,TEMPVARI01+=TEMPVARI04,TEMPVARI02+=TEMPVARI05"
ECHO [%~1G[38;2;!TEMPVARI00!;!TEMPVARI01!;!TEMPVARI02!m^|____ _____ _____ \   / _____ _   _ _   ^| 
SET /A "TEMPVARI00+=TEMPVARI03,TEMPVARI01+=TEMPVARI04,TEMPVARI02+=TEMPVARI05"
ECHO [%~1G[38;2;!TEMPVARI00!;!TEMPVARI01!;!TEMPVARI02!m    ^| ^|   ^| ^|      \ /  ^|   ^| ^|   ^| ^|\  ^| 
SET /A "TEMPVARI00+=TEMPVARI03,TEMPVARI01+=TEMPVARI04,TEMPVARI02+=TEMPVARI05"
ECHO [%~1G[38;2;!TEMPVARI00!;!TEMPVARI01!;!TEMPVARI02!m    ^| ^|___^| ^|____   ^|   ^|___^| ^|___^| ^| \ ^| 
SET /A "TEMPVARI00+=TEMPVARI03,TEMPVARI01+=TEMPVARI04,TEMPVARI02+=TEMPVARI05"
ECHO [%~1G[38;2;!TEMPVARI00!;!TEMPVARI01!;!TEMPVARI02!m    │ │   │ │       │   │   │ │   │ │  \│ 
ECHO [%~1G[38;2;!SYCONFIG_COLOR_LBASE!m╙───┘ ┴   ┴ └────  ─┴─  ┴   ┴ ┴   ┴ ┴   ┴ 
GOTO :EOF

REM 00
:SAVE_CONFIG
ECHO ; SaeyahnTracker configuration file > "!SY_APPCONFIGPATH!\config.txt"
FOR /F "TOKENS=*" %%A IN ('SET') DO (
	SET "TEMPVARI00=%%A"
	IF "!TEMPVARI00:~0,8!"=="SYCONFIG" (ECHO %%A) >> "!SY_APPCONFIGPATH!\config.txt"
)
GOTO :EOF

REM 00 01
:MSGBOX CONTEXT TYPE BUTTON
SET "TEMPVARI01=!TEMP!\!RANDOM!.VBS"
ECHO WScript.Quit MsgBox("%~1",%~3+%~2,"!SY_APPNAME!") > "!TEMPVARI01!"
WSCRIPT "!TEMPVARI01!"
SET "TEMPVARI00=!ERRORLEVEL!"
DEL /Q "TEMPVARI01" 2>NUL >NUL
GOTO :EOF
#>
# POWERSHELL SECTION
function main
{
param([string] $FilePath)
Add-Type -TypeDefinition @'
	using System;
	using System.Runtime.InteropServices;
	public class User32 {
		[DllImport("user32.dll")]
		public static extern short GetAsyncKeyState(int vKey);
	}
'@
while($true){if([User32]::GetAsyncKeyState(0x0D) -band 0x8000){ Remove-Item -Path $FilePath -Force; break }}
}